server:
  port: 9090
spring:
  application:
    name: spirng-Kiss-learn
  rabbitmq:
    host: 121.199.44.208
    port: 5672
    username: root
    password: rabbitmqpwd
  redis:
    port: 6379
    host: 172.168.10.223
    password: agile12345
#    port: 6371
#    password: redis123
#    host: 121.199.44.208

