spring:
  datasource:
    url: jdbc:mysql://1.117.157.125:3306/study?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: mbJtJxwbzsSb6j4k
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema: classpath:/sql/schema.sql
#    data: classpath:/sql/data.sql
    continue-on-error: true
    initialization-mode: always
    sql-script-encoding: UTF-8
mybatis:
  mapper-locations: classpath:/mapper/*.xml

