server:
  port: 9991
spring:
  application:
    name: redis-learn
  #  rabbitmq:
  #    host: 121.199.44.208
  #    port: 5672
  #    username: root
  #    password: rabbitmqpwd
  redis:
    port: 6378
    host: 121.199.44.208
    #    password: redis12
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最小空闲连接
        min-idle: 2
    #连接超时时间（毫秒）
    timeout: 30000
